object Versions {
    const val compose = "1.4.3"
    const val composeMaterial3 = "1.1.1"
    const val composeCompiler = "1.4.6"
    const val hilt = "2.41"
    const val okHttp = "5.0.0-alpha.2"
    const val retrofit = "2.9.0"
    const val room = "2.5.0"
    const val coild = "2.5.0"
    const val coreKtx = "1.13.1"
    const val lifecycleRuntimeKtx = "2.8.4"
    const val activityCompose = "1.9.1"
    const val composeBom = "2024.04.01"
    const val junit = "4.13.2"
    const val junitVersion = "1.2.1"
    const val espressoCore = "3.6.1"
}